<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Foto</name>
   <tag></tag>
   <elementGuidId>dac8ec9e-7052-4882-ad0d-de1c206732f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'form-avatar-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-avatar-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='form-avatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9e13af46-afda-47b2-888f-341dd7529fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-avatar rounded-4 text-primary bg-alt-primary p-5</value>
      <webElementGuid>9a2ab3ca-962f-44ff-b7a8-073878110cae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-avatar-input</value>
      <webElementGuid>11ffe1c2-32d9-42fc-8bea-62d705b7a641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-avatar-input&quot;)</value>
      <webElementGuid>3e2ebd8a-eef1-4ec5-af02-2891de714701</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='form-avatar-input']</value>
      <webElementGuid>80515e94-3853-48f8-91b6-27548c01c6f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-avatar-view']/div</value>
      <webElementGuid>966e9a3c-3be8-47fd-9d62-7e779b69cb16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lengkapi Info Akun'])[1]/following::div[5]</value>
      <webElementGuid>53c28e96-6353-447d-bbe6-b3467fbcfe8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama'])[1]/preceding::div[1]</value>
      <webElementGuid>04634939-dda4-40b8-9b5d-500bf536d782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kota'])[1]/preceding::div[2]</value>
      <webElementGuid>bca3b3cf-195b-473e-9bb0-975201fd0838</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>86d46c4c-58e5-4afe-a1c1-46375f6fb472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'form-avatar-input']</value>
      <webElementGuid>1684dccd-9b6e-4088-b700-81664af16c2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
